### ISSUE TITLE
Review Aurora's Heilmeier Catechism by 9/21 EoD

### ISSUE THREAD

**Issue by auroravogel** [luquelab/aurora_vogel_athena#10]
My Heilmeier Catechism is linked [here](https://github.com/luquelab/avogel_master/blob/main/data/Auroras_Hellmeier_Catechism(first_draft).pdf).

**Comment by luque82** [comment]
Done. Revised document: https://github.com/luquelab/aurora_vogel_athena/blob/main/data/Auroras_Hellmeier_Catechism_2021-07-17_AL.pdf
