### ISSUE TITLE
Revise Heilmeier Catechism by 2021-10-22

### ISSUE THREAD

**Issue by luque82** [luquelab/aurora_vogel_athena#11]
Check the reviewed document:
https://github.com/luquelab/aurora_vogel_athena/blob/main/data/Auroras_Hellmeier_Catechism_2021-07-17_AL.pdf

Use the video feedback as a guide:
https://sdsu.zoom.us/rec/share/NwJalXzScyMLjB4Vl4qXc7dEM7ycmFTC0SKFL6BsWLeAZghokCL6SP8vns8MQXpy._0R2vzdOVpGhniyQ

Three main goals:
1) Update the cost section, being more specific on $$$.
2) Use the conical case as your main goal and summarize the state-of-the-art regarding the geometry of conical capsids: math and structural biology known.
3) Use the elongated case as an incremental step bridging from icosahedral to conical. It's your non-risky product. Here are some suggested steps:
Step 1: Adapt the Archimedean lattice theory to the already established hexagonal lattices in elongated capsids.
Step 2: Generate Chimera models for elongated capsids.
Step 3: Adapt the hexagonal (and Archimedean) framework to conical capsids.
Step 4: Generate Chimera models for conical capsids
(Steps 1 and 2 are mathematically feasible 100% (no risk as far as we put the effort)... Steps 3 and 4 are possible... (that's where the fun will happen... but it's riskier...)

**Comment by luque82** [comment]
To get familiar with the current limitations regarding conical geometries, check the section "SA3-2 New sets of conical capsid structures" in the lab's ongoing NSF Math Bio award.

**Comment by auroravogel** [comment]
Put Hellmeier onto Home page.

**Comment by auroravogel** [comment]
New issues created as a response to this. Closing.
