### ISSUE TITLE
Distribute Heilmeier blocks into Home, Background, and Approach by 2021-11-11

### ISSUE THREAD

**Issue by luque82** [luquelab/aurora_vogel_athena#14]
Follow the auto-lattice site as a guide:
https://luquelab.github.io/auto-lattice/
https://luquelab.github.io/auto-lattice/background/

**Comment by luque82** [comment]
Use the comments in this file as a guide:
[Aurora_Heilmeier_AL.pdf](https://github.com/luquelab/aurora_vogel_athena/files/7479906/Aurora_Heilmeier_AL.pdf)

**Comment by auroravogel** [comment]
Postponing: New date 12/22.

**Comment by auroravogel** [comment]
Blocks of Hellmeier copied to the corresponding sections recommended in the video feedback. Restructured tabs to match the Auto Lattice page.
